name: Upload Windows Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build frontend
      run: |
        npm install
        npm run build
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: PyO3/maturin-action@v1
      with:
        command: develop
        args: --release
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller biliup.spec
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: target/release/${{ matrix.artifact_name }}
        file: dist/biliup.exe
        asset_name: biliup_$tag.exe
        tag: ${{ github.ref }}
